export * from './api';
export * from './creditCard';
export * from './defaults';
export * from './error';
export * from './states';
export * from './validation';
export declare const URL_BASE = "https://www.undergroundcellar.com/";
export declare const WINE_IMG_URL_BASE: string;
export declare const DETAIL_BASE_URL = "/wine-deals/";
export declare const wineSizes: string[];
export declare function getWineSize(id: number): string;
