"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.states = [
    {
        name: 'Alabama',
        abbreviation: 'AL',
    },
    {
        name: 'Alaska',
        abbreviation: 'AK',
    },
    {
        name: 'Arizona',
        abbreviation: 'AZ',
    },
    {
        name: 'Arkansas',
        abbreviation: 'AR',
    },
    {
        name: 'California',
        abbreviation: 'CA',
    },
    {
        name: 'Colorado',
        abbreviation: 'CO',
    },
    {
        name: 'Connecticut',
        abbreviation: 'CT',
    },
    {
        name: 'Delaware',
        abbreviation: 'DE',
    },
    {
        name: 'District Of Columbia',
        abbreviation: 'DC',
    },
    {
        name: 'Florida',
        abbreviation: 'FL',
    },
    {
        name: 'Georgia',
        abbreviation: 'GA',
    },
    {
        name: 'Guam',
        abbreviation: 'GU',
    },
    {
        name: 'Hawaii',
        abbreviation: 'HI',
    },
    {
        name: 'Idaho',
        abbreviation: 'ID',
    },
    {
        name: 'Illinois',
        abbreviation: 'IL',
    },
    {
        name: 'Indiana',
        abbreviation: 'IN',
    },
    {
        name: 'Iowa',
        abbreviation: 'IA',
    },
    {
        name: 'Kansas',
        abbreviation: 'KS',
    },
    {
        name: 'Kentucky',
        abbreviation: 'KY',
    },
    {
        name: 'Louisiana',
        abbreviation: 'LA',
    },
    {
        name: 'Maine',
        abbreviation: 'ME',
    },
    {
        name: 'Maryland',
        abbreviation: 'MD',
    },
    {
        name: 'Massachusetts',
        abbreviation: 'MA',
    },
    {
        name: 'Michigan',
        abbreviation: 'MI',
    },
    {
        name: 'Mississippi',
        abbreviation: 'MS',
    },
    {
        name: 'Minnesota',
        abbreviation: 'MN',
    },
    {
        name: 'Missouri',
        abbreviation: 'MO',
    },
    {
        name: 'Montana',
        abbreviation: 'MT',
    },
    {
        name: 'Nebraska',
        abbreviation: 'NE',
    },
    {
        name: 'Nevada',
        abbreviation: 'NV',
    },
    {
        name: 'New Hampshire',
        abbreviation: 'NH',
    },
    {
        name: 'New Jersey',
        abbreviation: 'NJ',
    },
    {
        name: 'New Mexico',
        abbreviation: 'NM',
    },
    {
        name: 'New York',
        abbreviation: 'NY',
    },
    {
        name: 'North Carolina',
        abbreviation: 'NC',
    },
    {
        name: 'North Dakota',
        abbreviation: 'ND',
    },
    {
        name: 'Ohio',
        abbreviation: 'OH',
    },
    {
        name: 'Oklahoma',
        abbreviation: 'OK',
    },
    {
        name: 'Oregon',
        abbreviation: 'OR',
    },
    {
        name: 'Pennsylvania',
        abbreviation: 'PA',
    },
    {
        name: 'Rhode Island',
        abbreviation: 'RI',
    },
    {
        name: 'South Carolina',
        abbreviation: 'SC',
    },
    {
        name: 'South Dakota',
        abbreviation: 'SD',
    },
    {
        name: 'Tennessee',
        abbreviation: 'TN',
    },
    {
        name: 'Texas',
        abbreviation: 'TX',
    },
    {
        name: 'Utah',
        abbreviation: 'UT',
    },
    {
        name: 'Vermont',
        abbreviation: 'VT',
    },
    {
        name: 'Virginia',
        abbreviation: 'VA',
    },
    {
        name: 'Washington',
        abbreviation: 'WA',
    },
    {
        name: 'West Virginia',
        abbreviation: 'WV',
    },
    {
        name: 'Wisconsin',
        abbreviation: 'WI',
    },
    {
        name: 'Wyoming',
        abbreviation: 'WY',
    },
];
exports.countryCodeMap = [
    ['AL', 'Albania'],
    ['DZ', 'Algeria'],
    ['AL', 'Andorra'],
    ['AR', 'Argentina'],
    ['AM', 'Armenia'],
    ['AU', 'Australia'],
    ['AT', 'Austria'],
    ['AZ', 'Azerbaijan'],
    ['BB', 'Barbados'],
    ['BY', 'Belarus'],
    ['BE', 'Belgium'],
    ['BZ', 'Belize'],
    ['BM', 'Bermuda'],
    ['BT', 'Bhutan'],
    ['BO', 'Bolivia'],
    ['BA', 'Bosnia-Herzegovina'],
    ['BR', 'Brazil'],
    ['BG', 'Bulgaria'],
    ['US', 'California'],
    ['KH', 'Cambodia'],
    ['CA', 'Canada'],
    ['CV', 'Cape Verde Islands'],
    ['CL', 'Chile'],
    ['CN', 'China'],
    ['CL', 'CHL'],
    ['CO', 'Colombia'],
    ['CR', 'Costa Rica'],
    ['HR', 'Croatia'],
    ['CU', 'Cuba'],
    ['CY', 'Cyprus'],
    ['CZ', 'Czech Republic'],
    ['DK', 'Denmark'],
    ['DO', 'Dominican Republic'],
    ['EC', 'Ecuador'],
    ['EG', 'Egypt'],
    ['UK', 'England'],
    ['EE', 'Estonia'],
    ['ET', 'Ethiopia'],
    ['FI', 'Finland'],
    ['FR', 'France'],
    ['GE', 'Georgia'],
    ['DE', 'Germany'],
    ['GR', 'Greece'],
    ['GT', 'Guatemala'],
    ['HT', 'Haiti'],
    ['HU', 'Hungary'],
    ['IS', 'Iceland'],
    ['IN', 'India'],
    ['ID', 'Indonesia'],
    ['IE', 'Ireland'],
    ['IL', 'Israel'],
    ['IT', 'Italy'],
    ['JM', 'Jamaica'],
    ['JP', 'Japan'],
    ['JE', 'Jersey'],
    ['JO', 'Jordan'],
    ['KZ', 'Kazakhstan'],
    ['KR', 'Korea'],
    ['LV', 'Latvia'],
    ['LB', 'Lebanon'],
    ['LI', 'Liechtenstein'],
    ['LT', 'Lithuania'],
    ['LU', 'Luxembourg'],
    ['MK', 'Macedonia'],
    ['MG', 'Madagascar'],
    ['MT', 'Malta'],
    ['MU', 'Mauritius'],
    ['MX', 'Mexico'],
    ['MD', 'Moldova'],
    ['MN', 'Mongolia'],
    ['ME', 'Montenegro'],
    ['MA', 'Morocco'],
    ['MM', 'Myanmar'],
    ['NA', 'Namibia'],
    ['NL', 'Netherlands'],
    ['NZ', 'New Zealand'],
    ['NI', 'Nicaragua'],
    ['NO', 'Norway'],
    ['PA', 'Panama'],
    ['PY', 'Paraguay'],
    ['PE', 'Peru'],
    ['PH', 'Philippines'],
    ['PL', 'Poland'],
    ['PT', 'Portugal'],
    ['RO', 'Romania'],
    ['RU', 'Russia'],
    ['LC', 'Saint Lucia'],
    ['SM', 'San Marino'],
    ['RS', 'Serbia'],
    ['SK', 'Slovakia'],
    ['SI', 'Slovenia'],
    ['ZA', 'South Africa'],
    ['ES', 'Spain'],
    ['SE', 'Sweden'],
    ['CH', 'Switzerland'],
    ['SY', 'Syria'],
    ['PF', 'Tahiti'],
    ['TW', 'Taiwan (ROC)'],
    ['TZ', 'Tanzania'],
    ['TH', 'Thailand'],
    ['TT', 'Trinidad & Tobago'],
    ['TN', 'Tunisia'],
    ['TR', 'Turkey'],
    ['UA', 'Ukraine'],
    ['GB', 'United Kingdom'],
    ['UY', 'Uruguay'],
    ['US', 'United States'],
    ['VI', 'US Virgin Islands'],
    ['UZ', 'Uzbekistan'],
    ['VE', 'Venezuela'],
    ['VN', 'Vietnam'],
    ['ZW', 'Zimbabwe'],
];
function getCountryName(countryCode) {
    var cc = countryCode.toUpperCase();
    for (var i = 0; i < exports.countryCodeMap.length; ++i) {
        if (exports.countryCodeMap[i][0] == cc) {
            return exports.countryCodeMap[i][1];
        }
    }
    return '?';
}
exports.getCountryName = getCountryName;
;
exports.varietals = [
    '@gift',
    '@insert',
    '@food',
    '@virtual',
    'Aglianico',
    'Albarino',
    'Aleatico',
    'Angelic Blend',
    'Arneis',
    'Barbera',
    'Blanc',
    'Blanc de Blancs',
    'Blanc de Noirs',
    'Blaufrankisch',
    'Blend',
    'Bonarda',
    'Bordeaux',
    'Bordeaux Blend',
    'Bordeaux Rouge',
    'Botrytised Semillon',
    'Brandy',
    'Brut',
    'Brut Cuvee',
    'Brut Rose',
    'Brut Rose of Pinot Noir',
    'Bukettraube',
    'Burgundy',
    'Cabernet Blanc',
    'Cabernet Franc',
    'Cabernet Franc/Cabernet Sauvignon/Merlot/Shiraz',
    'Cabernet Franc/Rose',
    'Cabernet Sauvignon',
    'Cabernet Sauvignon Etched Bottle',
    'Cabernet Sauvignon Port',
    'Cabernet Sauvignon Rosé',
    'Cabernet Sauvignon/Carmenere',
    'Cabernet Sauvignon/Malbec',
    'Cabernet Sauvignon/Merlot',
    'Cabernet Sauvignon/Merlot/Petit Verdot',
    'Cabernet Sauvignon/Merlot/Syrah',
    'Cabernet Sauvignon/Petite Sirah',
    'Cabernet Sauvignon/Rosé',
    'Cabernet Sauvignon/Sangiovese',
    'Cabernet Sauvignon/Shiraz',
    'Cabernet Sauvignon/Syrah',
    'Cabernet/Shiraz/Malbec',
    'Cameron Fisher',
    'Carignane',
    'Carignane/Grenache/Petite Syrah/Syrah',
    'Carmenere',
    'Catarrato',
    'Chablis',
    'Champagne',
    'Charbono',
    'Chardonnay',
    'Chardonnay Champagne',
    'Chardonnay/Pinot Grigio',
    'Chardonnay/Pinot Gris',
    'Chardonnay/Semillon',
    'Chardonnay/Viognier',
    'Chenin Blanc',
    'Chenin Blanc/Colombard',
    'Chianti',
    'Cinsault',
    'Claret',
    'Clone 4',
    'Clone 6',
    'Crianza',
    'Cuvee',
    'Cuvee Rose',
    'Cuvee Sauvage',
    'Dessert Wine',
    'Diablo Rosso',
    'Dolcetto',
    'Dolcino Rosso',
    'Dry Rose',
    'Dry Rosé of Pinot Noir',
    'Durif',
    'Field Blend',
    'French Colombard',
    'Fume Blac',
    'Fume Blanc',
    'GSM',
    'Gaglioppo',
    'Gamay',
    'Gargenga/Pinot Grigio',
    'Garnacha',
    'Garnacha/Carinena',
    'Gewurztraminer',
    'Graciano',
    'Grappa',
    'Grenache',
    'Grenache Blanc',
    'Grenache Noir',
    'Grenache Rose',
    'Grenache/Mourvedre/Syrah',
    'Grenache/Shiraz',
    'Grenache/Syrah',
    'Grüner Veltliner',
    'Harvest Sauvignon',
    'Johannesburg Riesling',
    'Lagrein',
    'MXV',
    'Malbec',
    'Malbec Merlot',
    'Malbec/Rosé',
    'Malvasia Bianca',
    'Mangoscato',
    'Marsanne',
    'Marsanne/Viognier',
    'Marselen Red Blend',
    'Mataro',
    'Matzin',
    'Merlot',
    'Merlot Blanc',
    'Merlot Champagne',
    'Merlot/Rosé',
    'Merlot/Xinomavro',
    'Montepulciano',
    'Montepulciano D\'Abruzzo',
    'Moscatel',
    'Moscato',
    'Moscato D\'Oro',
    'Moscato Frizzante',
    'Moscato Spumate',
    'Mourvedre',
    'Mourvedre Syrah Grenache',
    'Muscat',
    'Muscat Canelli',
    'Muscat Grappa',
    'Muscato',
    'Nebbiolo',
    'Negrette',
    'Nero d\'Avola',
    'Old Vine White',
    'Orvieto',
    'Other Red',
    'Other White',
    'Petit Verdot',
    'Petit Verdot Port',
    'Petite Sirah',
    'Petite Sirah Verdot',
    'Petite Verdot',
    'Picpoul Blanc',
    'Pinot Blanc',
    'Pinot Grigio',
    'Pinot Gris',
    'Pinot Noir',
    'Pinot Noir Brut',
    'Pinot Noir Burgundy',
    'Pinot Noir Rose',
    'Pinot Noir/Syrah',
    'Pinot Noir/Valdiguie',
    'Pinot Rose',
    'Pinotage',
    'Pinotage Shiraz',
    'Platinum',
    'Port',
    'Port/Syrah',
    'Portuguese Varietals',
    'Primitivo',
    'Proprietary Red',
    'Prosecco',
    'Red Blend',
    'Red Bordeaux',
    'Red Burgundy',
    'Red Meritage',
    'Red Rhone Blend',
    'Red Table Wine',
    'Red Wine',
    'Red wine',
    'Retsina',
    'Rhone Blend',
    'Rice Wine',
    'Riesling',
    'Riesling Champagne',
    'Riesling Traminer',
    'Rooster\'s Blend',
    'Rosato',
    'Rose',
    'Rose of Merlot',
    'Rose of Syrah',
    'Roseto',
    'Rosso',
    'Rosé Table Wine',
    'Rosé of Pinot Noir',
    'Rosé/Syrah',
    'Roussanne',
    'Roussanne/Viognier',
    'Sagrantino',
    'Sake',
    'Sangiovese',
    'Sangiovese Negroamaro',
    'Sangiovese Rose',
    'Sangiovese, Barbera, Sagrantino',
    'Sangiovese/Syrah',
    'Sauv Blanc',
    'Sauvignon Blanc',
    'Sauvignon Blanc,Chardonnay',
    'Sauvignon Blanc/Semillon',
    'Sauvignon Gris',
    'Secco',
    'Semillon',
    'Semillon/Chardonnay',
    'Sherry',
    'Shiraz',
    'Shiraz‐Cabernet Sauvignon',
    'Shiraz/Grenache',
    'Shiraz/Viognier',
    'Sparkling',
    'Sparkling Brut',
    'Sparkling Chardonnay',
    'Sparkling Cuvee',
    'Sparkling Muscat Canelli',
    'Sparkling Rose',
    'Sparkling Syrah',
    'Sparkling Wine',
    'Symmetry',
    'Symphony',
    'Syrah',
    'Syrah Blend',
    'Syrah Cabernet',
    'Syrah Cabernet Sauvignon Merlot',
    'Syrah Port',
    'Syrah Rosé',
    'Syrah Viognier',
    'Syrah/Viognier',
    'Table Red Rosé Wine',
    'Tannat',
    'Tapestry',
    'Tempranillo',
    'Tempranillo Cabernet',
    'Tempranillo Grenache',
    'Tempranillo Rosé',
    'Tokaji',
    'Torrontes',
    'Touriga Nacional',
    'Trebbiano Spoletino',
    'Trousseau',
    'Unoaked Chardonnay',
    'Verdejo',
    'Verdelho',
    'Verdot',
    'Vermentino',
    'Vermouth',
    'Vidal Blanc',
    'Vin Gris',
    'Vino',
    'Viognier',
    'Violet',
    'White Blend',
    'White Bordeaux',
    'White Burgundy',
    'White Meritage',
    'White Merlot',
    'White Pinot Noir',
    'White Riesling',
    'White Table Wine',
    'White Wine',
    'White Zinfandel',
    'White Zinfandel Champagne',
    'Zinfandel',
    'Zinfandel Port',
    'Zinfandel Shiraz',
    'Zinfandel/Malbec',
];
exports.wineTypes = [
    '(none)',
    'Beer',
    'Fruit/Vegetable Wine',
    'Non-alcoholic',
    'Red',
    'Red - Fortified',
    'Red - Sparkling',
    'Red - Sweet/Dessert',
    'Rosé',
    'Rosé - Fortified',
    'Rosé - Sparkling',
    'Rosé - Sweet/Dessert',
    'Sake',
    'Spirits',
    'White',
    'White - Fortified',
    'White - Off-dry',
    'White - Sparkling',
    'White - Sweet/Dessert',
];
//# sourceMappingURL=states.js.map